### ISSUE TITLE
[Feature Request] XS breakpoint

### ISSUE THREAD

**Issue by harshzalavadiya** [varunj166/mq-styled-components#1]
Can this have `XS` endpoint can be `375px` and above?

Reference chrome responsive breakpoint
![image](https://user-images.githubusercontent.com/5774849/86457609-8def1000-bd41-11ea-8fc1-bb14b0672877.png)

and thanks for creating this package :+1:

**Comment by varunj166** [comment]
@harshzalavadiya Hey, you're welcome!

Umm, are you certain you need to create style rules for the very specific range of 375px to 576px?

In every app I've worked on, targeting a max-width of 576px (with mq-styled-components, you'd create that media query with `${Mq.max.sm}` which covers a width of 576px and below, covers every smartphone out there without the need to change layouts or elements for even more specific widths below that.

If you're absolutely sure `Mq.max.sm` to target 576px and below doesn't do the job for you, I can add in an XS breakpoint as you requested.

**Comment by harshzalavadiya** [comment]
Generally it't not required on most off projects, because 576px works really great for most off mobile devices mobile phones but it assumes every phone as high end when targeting low end mobile devices/ipad side view sometime I have to write seprate media query to adjest for text etc.

![image](https://user-images.githubusercontent.com/5774849/86474389-58a5ea80-bd60-11ea-84d3-fa196e29158c.png)

if possible it will be nice to have since it's not breaking anything and just extra breakpoint

**Comment by varunj166** [comment]
Yeah it's not a hard addition to make, just adding the tests and updating the readme I wanted to make sure was worth it if you were absolutely sure.

Alright, I'll add the feature now. It'll be up as v2.1.0, in the next 30 mins.

**Comment by varunj166** [comment]
@harshzalavadiya v2.1.0 is up with the new breakpoint.

Open another issue anytime if you have any other problems.

Cheers!
